library(xts, quietly = TRUE)
library(readr, quietly = TRUE)
library(quantmod, quietly=TRUE)
library(MASS, quietly = TRUE)
library(FactorAnalytics, quietly = TRUE)
library(rvest, quietly = TRUE)

#' Download Fama-French 5 factor monthly data
#' source: http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_5_Factors_2x3_CSV.zip
#' 
#' @return xts object with monthly data for Fama-French model
#'
#' @examples
#' download_FF_5_factor_monthly()

download_FF_5_factor_monthly <- function(){
    ff_url <- "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_5_Factors_2x3_CSV.zip"
    temp <- tempfile()
    download.file(ff_url,temp)
    ff_data <- read.csv(unz(temp,"F-F_Research_Data_5_Factors_2x3.CSV"), skip=3, check.names=TRUE)
    unlink(temp)
    idx <- which(ff_data[,1]== " Annual Factors: January-December ")
    ff_data<-ff_data[1:(idx-1),]
    ff_data <- data.frame(apply(ff_data,2,as.numeric))
    ff_data<-as.xts(ff_data, order.by=as.yearmon(as.character(ff_data$X),"%Y%m"))
    return(ff_data[,-1])
}

#' Download Fama-French 5 factor daily data
#' source: http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_5_Factors_2x3_daily_CSV.zip
#' 
#' @return xts object with daily data for Fama-French model
#'
#' @examples
#' download_FF_5_factor_daily()

download_FF_5_factor_daily <- function(){
    ff_url <- "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_5_Factors_2x3_daily_CSV.zip"
    temp <- tempfile()
    download.file(ff_url,temp)
    ff_data <- read.csv(unz(temp,"F-F_Research_Data_5_Factors_2x3_daily.CSV"), skip=3, check.names=TRUE)
    unlink(temp)
    ff_data <- xts(ff_data, order.by=as.Date(as.character(ff_data$X),"%Y%m%d"))
    ff_data <- ff_data[,-1]
    return(ff_data)
}

#' Download Fama-French 5 factor model data from Ken French website
#'
#' @param freq Either "M" for monthly data or "D" for daily data
#'
#' @return xts object with the daily or monthly data
#' @export
#'
#' @examples
#' download_FF_5_factor("M")
#' download_FF_5_factor("D")

download_FF_5_factor <- function(freq="M"){
    if (toupper(substr(freq,1,1))=="M") {
        out <- download_FF_5_factor_monthly()
    } else {
        out <- download_FF_5_factor_daily()
    }
    return(out)
}

#' Get prices for one or more symbols
#' 
#'
#' @param symbols Tickers of the mutual funds and ETFs
#' @param startDate default is 1970-01-01
#' @param freq M for monthly or D for daily
#'
#' @return xts object with prices. Index will be yearmon for monthly data
#' @export
#'
#' @examples
#' getPrices("IVV")
#' getPrices("IVV", startDate="2015-12-31", freq="D")

getPrices <- function(symbols, startDate="1970-01-01", freq="M"){
    Sys.setenv(TZ="UTC")
    getSymbols(symbols,warnings=FALSE, from=startDate)
    data<-xts(frequency = "Date")
    for (symbol in symbols){
        #cat(symbol," ... ")
        data<-merge(data,Ad(get(symbol)))
    }
    index(data) <- as.Date(index(data))
    saveRDS(data,"prices.rds")
    data<-readRDS("prices.rds")
    colnames(data) <- sapply(colnames(data),function(x) substr(x,1,regexpr("\\.",x)-1))
    colnames(data) <- symbols
    if(toupper(freq) != "D"){
        mon_idx <- endpoints(data, on="months")
        data <- data[mon_idx,]
        index(data)<-as.yearmon(index(data),"%Y-%m-%d")
    }
    return(data)
}

#' Converts prices to returns
#'
#' @param prices xts of prices such as returned by getPrices function
#' @param freq M for monthly, or D for daily
#'
#' @return xts object of returns
#' @export
#'
#' @examples
#' convertPricesToReturns(p)

convertPricesToReturns <- function(prices, freq="D"){
    if(toupper(freq)=="D") {
        rets <- lapply(1:ncol(prices),function(x) periodReturn(prices[,x],period="daily"))
        
    } else {
        rets <- lapply(1:ncol(prices),function(x) periodReturn(prices[,x],period="monthly"))
    }
    names(rets) <- colnames(prices)
    return(rets)
}

#' Generates individual lm model for a fund using Fama-French data
#' Not public.  
#'
#' @param y Returns of fund
#' @param ff_data Fama-French data
#' @param s Start date
#' @param e End date
#' @param n Number of periods
#'
#' @return lm model
#'
#' @examples
#' ffModelLM_sub(y,ff_data)

ffModelLM_sub <- function(y,ff_data,s=NULL,e=NULL,n=NULL){
    data <- ffMergeXTS(y,ff_data,s,e,n)
    mdl <- lm(y~Mkt.RF+SMB+HML+RMW+CMA+RF,data=data)
    return(mdl)
}

#' Generates lm models for one or more funds using Fama-French data as independent variables
#'
#' @param rets List of returns such as generated by convertPricesToReturns()
#' @param ff_data Fama-French data in same frequency as Y
#' @param s Start date
#' @param e End date
#' @param n Number of observations
#'
#' @return List of lm models
#' @export
#'
#' @examples
#' ffModelLM(rets, ff_data)

ffModelLM <- function(rets,ff_data,s=NULL,e=NULL,n=NULL){
    out <- lapply(rets, function(x) ffModelLM_sub(y=x,ff_data=ff_data,s=s,e=e,n=n))
    names(out) <- names(rets)
    return(out)
}

#' Generates an lm model using stepwise regression
#'
#' @param y Fund returns
#' @param ff_data Fama-French data
#' @param s Start date
#' @param e End date
#' @param n Number of observations
#'
#' @return lm model
#'
#' @examples
#' ffModelStepLM_sub(y,ff_data)

ffModelStepLM_sub <- function(y,ff_data, s=NULL, e=NULL, n=NULL){
    data <- ffMergeXTS(y,ff_data,s,e,n)
    mdl <- lm(y~Mkt.RF+SMB+HML+RMW+CMA+RF,data=data)
    return(stepAIC(mdl, direction="both"))
}

#' Generates list of lm models using step-wise regression
#'
#' @param y Fund returns
#' @param ff_data Fama-French data
#' @param s Start date
#' @param e End date
#' @param n Number of periods
#'
#' @return List of lm models
#' @export
#'
#' @examples
#' ffModelStepLM(y,ff_data)

ffModelStepLM <- function(y,ff_data, s=NULL, e=NULL, n=NULL){
    out <- lapply(rets, function(x) ffModelStepLM_sub(y=x,ff_data=ff_data,s=s,e=e,n=n))
    names(out) <- names(rets)
    return(out)
}


#' Filter (subset) an xts object
#' Subsets an xts object from start (s) to end (e).  If either is omitted, the earliest or latest observation is used
#' If n is not null it will return n observations from the last date (e).
#'
#' @param xtsData xts object to be filtered (subsetted) 
#' @param s Start date
#' @param e End date
#' @param n Number of observations
#'
#' @return xts object
#' @export
#'
#' @examples
#' dateFilter(xtsOjbect,s="2012-12-31",e="2017-12-31")
#' dateFilter(xtsOjbect,e="2017-12-31", n=60)

dateFilter <- function(xtsData,s=NULL,e=NULL,n=NULL){
    if(is.null(s)) s<- start(xtsData[1])
    if(is.null(e)) e<- end(xtsData)
    data <- xtsData[paste0(s,"/",e)]
    if(!is.null(n)){
        data<-last(data,n)
    }
    return(data)
}


#' Find common period between xts objects    
#' Given a list of xts objects, it returns a list of those objects with the longest common period (starting at most recent start,
#' and ending at earliest end)
#'
#' @param rets List of xts objects
#'
#' @return List of xts objects with common dates
#' @export
#'
#' @examples
#' faCommonDate(rets)

faCommonDate <- function(rets){
    s<-as.Date(max(sapply(rets,start)))
    e<-as.Date(min(sapply(rets,end)))
    out<-lapply(rets, function(x) x[paste0(s,"/",e)])
    return(out)
}


#' Merge return series with Fama-French data
#' Merges a xts object of returns with the ff data xts object.
#'
#' @param y Fund return
#' @param ff_data Fama-French data
#' @param s Start date
#' @param e End date
#' @param n Number of observations
#'
#' @return xts object
#' @export
#'
#' @examples
#' ffMergeXTS(y,ff_data)

ffMergeXTS <- function(y,ff_data,s=NULL,e=NULL,n=NULL){
    data <- merge.xts(ff_data,y,join = "inner")
    data <-dateFilter(data,s,e,n)
    colnames(data)[ncol(data)] <- "y"
    return(data[complete.cases(data),])
}


#' Coefficients from lm models
#'
#' @param lst List of lm models
#'
#' @return Table with coefficients for each model
#' @export
#'
#' @examples
#' coefficients.lm(lst)

coefficients.lm <- function(lst){
    temp <- t(sapply(lst,coefficients))
    row.names(temp)<-names(lst)
}

#' Returns based style anal
#'
#' @param y Fund returns
#' @param ff_data Fama-French data
#' @param s Start date
#' @param e End date
#' @param n Number of observations
#' @param method Method from Factor Analyticss package's style.fit function
#' @param leverage Leverage from Factor Analyticss package's style.fit function
#'
#' @return Style weights
#' @export
#'
#' @examples
#' RBSA(y,ff_data)
RBSA <- function(y,ff_data, s=NULL, e=Null, n=Null, method="constrained", leverage=FALSE){
    data <- ffMergeXTS(y,ff_data,s,e,n)
    out <- chart.Style(data$y,)
}


#' Scrape quote summary from Yahoo Finance
#'
#' @param symbol Ticker of fund
#'
#' @return List with data from quote summary
#' @export
#'
#' @examples
#' scrapeQuoteSummary("SPY")
scrapeQuoteSummary <- function(symbol){
    url <- paste0("https://finance.yahoo.com/quote/",symbol,"?p=",symbol)
    webpage <- read_html(url)
    result <- html_nodes(webpage, "#quote-summary")
    result <- html_nodes(result, "table") %>% html_table()
    fundName <- html_nodes(webpage,"h1") %>% html_text()
    startPos <- regexpr(" - ",fundName)
    fundName <- substr(fundName,startPos+3,nchar(fundName))
    out <-  c(symbol,fundName, result[[1]]$X2,result[[2]]$X2)
    names(out)<-c("Symbol","Fund Name",result[[1]]$X1,result[[2]]$X1)
    return(out)
}